### ISSUE TITLE
Allow home-manager to run independently

### ISSUE THREAD

**Issue by nmasur** [nmasur/dotfiles#11]
Home-manager is currently embedded as a module in nixosConfiguration, but maybe I can also extract is as a homeConfiguration and run it separately when not needed?

**Comment by danielo515** [comment]
How good is that strategy going? Any downsides?

**Comment by nmasur** [comment]
@danielo515 I've been slowly working on refactoring the whole repo in the [platform](https://github.com/nmasur/dotfiles/tree/platform) branch which is partially a way of getting home-manager to run on its own.

There are a few issues that I haven't fully worked out yet:

- There are some configuration items from NixOS services that I want home-manager to be aware of.
- I want home-manager to understand the current networking name.
- I need a way to fully encapsulate the HM config and use it in NixOS instead of simply duplicating it, which I still haven't quite solved.

It's definitely not ready yet but I am getting closer.

**Comment by danielo515** [comment]
> There are some configuration items from NixOS services that I want home-manager to be aware of.

Can you give me an example?

Have you considered flake-parts? I just started exploring it, but it seems they have tools to make the integration between different elements easier

**Comment by nmasur** [comment]
So a few that come to mind:

- My home-manager config includes scripts and command shortcuts for interacting with services hosted by NixOS, so if I can reference the hostnames or other features of the service then I only need to identify them once in my config.
- I use services like i3, polybar, rofi, and dunst which are configured by home-manager but refer to services like lightdm, betterlockscreen, or gtk settings from NixOS. For example, betterlockscreen on NixOS doesn't function properly if it's expecting dunst and dunst is disabled by home-manager.
- I have an identity file for decrypting my secrets which is managed by NixOS but I want to use it to decrypt secrets for home-manager as well.

**Comment by danielo515** [comment]
Have you seen this template? Seems promising https://github.com/juspay/nixos-unified-template/blob/main/flake.nix
