### ISSUE TITLE
Hammerspoon command pallette off screen, etc.

### ISSUE THREAD

**Issue by eblume** [nmasur/dotfiles#79]
Hello @nmasur , thanks again for all the work put in on these dotfiles! I have a specific question about hammerspoon:

Should I be seeing something while I string together hammerspoon chords on a macos laptop? For instance, if I use `[ctrl+cmd]o` (is that how one "spells" that chord?) to launch Obsidian, should I be seeing like a command pallete or some such while I do so, to help me with completion?

I ask because:

1. I do not see such a thing; but
2. [there is clearly some UI work being done](https://github.com/nmasur/dotfiles/blob/16a372ce64c853e5a6468c2afc46f66182f0d514/modules/darwin/hammerspoon/Spoons/Launcher.spoon/init.lua#L23-L43); and
3. I've recently set up a new mac and suddenly I see the bottom 4 pixels of what looks like a window at the top-center of my monitor while building a hammerspoon chord.

If there is indeed supposed to be a window there, I'm guessing something I did while I [forked my config](https://github.com/eblume/dotfiles/tree/main/modules/darwin/hammerspoon) broke hammerspoon.

PS, I'm proud of [the Obsidian.nvim integration](https://github.com/eblume/dotfiles/blob/main/modules/common/neovim/config/obsidian.nix) I've just recently added! I was previously using nb-cli but became frustrated with its sync behavior (probably fixable) and decided to give Obsidian a shot, and discovered this delightful plugin [Obsidian.nvim](https://github.com/epwalsh/obsidian.nvim) honestly seems like such a killer integration that it feels like Obsidian is just a sync client in the back end, at least so far. I'm curious if you have some other way you bring obsidian in to your CLI workflow, or if it helps to have it in the GUI in some specific way I should consider?

Hope all is well.

**Comment by nmasur** [comment]
@eblume I can help you understand how this works, it's not quite as elaborate as you might think it is.

With Hammerspoon, the idea is that I can enter a special "mode" on my keyboard with a special key combination. Once I'm in this mode (let's call it Launcher Mode), I can press a key to launch or jump to an open application (and exit Launcher Mode) or I can press Escape to cancel Launcher Mode.

So here's how it works:

1. Press CTRL+Space to [enter Launcher Mode](https://github.com/nmasur/dotfiles/blob/16a372ce64c853e5a6468c2afc46f66182f0d514/modules/darwin/hammerspoon/Spoons/Launcher.spoon/init.lua#L17)
2. [Draw a thin yellow rectangle at the top of the screen](https://github.com/nmasur/dotfiles/blob/16a372ce64c853e5a6468c2afc46f66182f0d514/modules/darwin/hammerspoon/Spoons/Launcher.spoon/init.lua#L33-L42). This is not the bottom of a window, it's just an indicator to tell me that I'm currently in Launcher Mode so I don't accidentally press a key to type something that I don't realize will launch a program.
3. Once in Launcher Mode, I can press a single character [such as "e"](https://github.com/nmasur/dotfiles/blob/16a372ce64c853e5a6468c2afc46f66182f0d514/modules/darwin/hammerspoon/Spoons/Launcher.spoon/init.lua#L70-L72) to open an application (if it's already open, it switches to the application) and [then exits](https://github.com/nmasur/dotfiles/blob/16a372ce64c853e5a6468c2afc46f66182f0d514/modules/darwin/hammerspoon/Spoons/Launcher.spoon/init.lua#L106-L109).
4. Upon exiting, the Launcher Mode keybinds are lost and the rectangle [disappears](https://github.com/nmasur/dotfiles/blob/16a372ce64c853e5a6468c2afc46f66182f0d514/modules/darwin/hammerspoon/Spoons/Launcher.spoon/init.lua#L45-L49).


Love the idea of Obsidian.nvim, I should take a deeper look at it! Honestly, I haven't done too much to try to connect Obsidian to Neovim other than trying to find a pretty good Markdown editor/wiki plugin. But that looks like something worth checking out!

**Comment by eblume** [comment]
Got it! Wow, it turns out that box has been there this whole time, then! I only noticed it on the new laptop because on my other laptop the background was bright enough that I couldn't see the box.

Thanks!
