### ISSUE TITLE
nixpgs registry issue on NixOS

### ISSUE THREAD

**Issue by eblume** [nmasur/dotfiles#98]
Hi @nmasur, hope you're well!

I recently ran in to an issue where I could not `nix run nixpkgs#gparted` due to some obscure error about a nix store path not existing, with no obvious ways to proceed. I [asked about it on matrix](https://matrix.to/#/!RRerllqmbATpmbJgCn:nixos.org/$H4DAcxHfcAFD_SftUyN1RO40hknCXvZZ3YLdJBnGBvM?via=matrix.org&via=tchncs.de&via=catgirl.cloud), and was directed to this fix: https://github.com/eblume/dotfiles/commit/0ec0d92e1650afed5304303f8999cdfa91c25640

As stated in the matrix thread, this seems to have been the proximal cause of this issue:

```
❯ nix registry list | grep nixpkgs
system flake:nixpkgs path:/nix/store/0sxsfzswhjck7f4sbsvznz285s4i7y64-source
global flake:nixpkgs github:NixOS/nixpkgs/nixpkgs-unstable
```
(The `path:/nix/store/0sxs...` does not exist, I'm assuming it did exist at some point and then got gc'ed)

I am not actually certain why the commit I linked to above resolves this issue, nor what the actual root cause of the issue is, nor do I understand the tradeoff of removing this section of your flake config. However I did want to call it out to you in case it helps you with some issue or in case you felt like you had the time to explain to me what's going on there.

(I vaguely understand that it's related to how you use utilities like `nix-fzf` and such, but nothing seems to have broken when I removed it.)

**Comment by nmasur** [comment]
Interesting, I'm getting the exact same error running a different program.

There must be something that changed regarding the behavior of the code that you removed. I know that the original purpose of that code block was to set the system registry to the same nixpkgs used by the flake. That way, even though I'm not using "channels", it would have a "channel" to respond to when querying nixpkgs for temporary packages.

I'm not sure why it's breaking everything now but I'm going to try removing it myself as well.
